Luckiifirpo/PF-Huellitas-de-amor

api/src/routes/controllers/UsersControllers.js, api/src/routes/routers/routerUsuario.js
1. Añadida ruta post de usuarios y verificado su funcionamiento
=> feature/api/src/routes 

api/package.json, api/src/routes/controllers/AnimalControllers.js, api/src/routes/controllers/UsersControllers.js, api/src/routes/utils/utils.js
Se añadió generación automatica de ids por medio de la dependencia uuid-js, tambien se creó una carpeta en api/src/routes llamada utils, en esa misma se añadio la funcion generadora de ids!
=> feature/api/routes/controllers añadida generacion automatica de ids

client/package.json, client/src/pages/SignUp/SignUp.jsx
validaciones de usurio para registrarse
=> FEATURE VALIDATION REGISTER USERS

client/src/components/Footer/Footer.jsx, client/src/components/Footer/Footer.module.css, client/src/pages/Adoptions/Adoptions.jsx, client/src/pages/Home/Home.jsx
se acomodo un boton de home que faltaba, la direcion de un boton de adpcion, se completo los links del footer y el diseño
=> feature: home, footeer and adoption details

client/src/pages/SignUp/SignUp.jsx, client/src/redux/store.js, client/src/redux/userReducer.js, client/src/services/api.js
ya se pueden registrar los usuarios
=> feature: funcionalidad del registro, ya se crean los usuarios

client/src/pages/SignUp/SignUp.jsx, client/src/redux/slices/userSlice.js
corregidas dependencias inexistentes
- implemente una libreria llamada lodash que entre otras cosas permite comparar objectos y arrays HAGAN NPM INSTALL
=> fix: corregidas dependencias inexistentes

client/package.json, client/src/pages/Login/Login.jsx, client/src/pages/Login/Login.module.css, client/src/services/firebaseApp.js
Se implement Firebase para la autenticacion de terceros, hay 3 botones Google, GitHub, Microsoft
=> feature: botones de autenticacion de terceros funcionales (HAGAN NPM INSTALL)

client/src/components/PostAdoption/PostAdoption.jsx, client/src/pages/Adoptions/Adoptions.jsx, client/src/redux/slices/adoptionSlice.js
Se corrigio problemas con el filtrado,
Al postear una mascota, se muestra un estado de 'loading' y mensajes tanto al concluir sin fallas como al fallar la carga.
=> fix and feature: loading status y mensajes de carga, correccion de filtros

client/src/pages/Login/Login.jsx
Problemas de configuracion con el login de microsoft
=> fix: removido el boton de login de microsofot

client/src/app/App.jsx, client/src/pages/Adoptions/Adoptions.jsx, client/src/redux/slices/petsSlice.js
Renderizado desde la api
Filtros solucionados
=> fix: renderizado desde api, filtros solucionados

client/src/components/PetCard/PetCard.jsx, client/src/components/PostAdoption/PostAdoption.jsx, client/src/pages/Adoptions/Adoptions.jsx, client/src/pages/Adoptions/Pet.Filters.js, client/src/pages/Adoptions/Pet.Sort.js
- se agrego un input para seleccionar el rango de tiempo "Años" o "Meses" en el formulario de creacion de mascotas
- Se corrigio un error de renderizado con formularios anidados y con Grid items en el formularo de creacion de mascotas
- las listas desplegables del formulario de mascotas ahora tienen valores por defecto.
- Los filtros de Edad y Peso en la pagina de Adopciones ahora interactuan bien con los datos numericos que vienen del servidor
- Se corrigio un error que impedia resetear los ordenamientos
=> fixing: errores en filtros y creacion de mascotas

api/src/models/Usuario.js, api/src/routes/controllers/AuthControllers.js, api/src/routes/controllers/UsersControllers.js, api/src/routes/routers/routerUsuario.js, client/src/app/App.jsx, client/src/components/Navbar/Navbar.jsx, client/src/components/UserAccountMenu/UserAccountMenu.jsx, client/src/redux/slices/userSlice.js
- Se diseño un menu basico para que el usuario entre a sus datos de perfil y pueda cerrar sesion
- Se creo una ruta backend para que obtener los datos de usuario mediante su id
- Se agrego al modelo de Usuarios el campo fotoURL (En teoria ya podrian ver su fotico de google o github si la tiene en la pagina)
- la sesion de usuario se almacena en sessionStorage para recordar sus datos cuando recargue la pagina
=> feature: menu de usuario basico

api/src/routes/controllers/AuthControllers.js, client/src/pages/Login/Login.jsx, client/src/redux/slices/userSlice.js
- Se puede hacer login con usuario y contraseña
- faltan las validaciones correspondientes al formulario de login
=> feature: login con usuario y contraseña

api/index.js, api/src/db.js, api/src/models/Admin.js, api/src/models/Contactus.js, api/src/routes/controllers/AdminController.js, api/src/routes/controllers/ContactUsController.js, api/src/routes/index.js, api/src/routes/routers/adminRouter.js, api/src/routes/routers/contactUsRouter.js, client/src/pages/Contact/Contact.jsx
Para darle funcionalidad al formulario Contactenos se creo lo siguiente:
*Modelo de contactus
*rutas y controladores solo con get y post
*Relaciones con modelo de usuario administrador.
Como complemento se creo el modelo de usuario administrador con lo siguiente:
*Modelo
*Rutas y controladores CRUD
*Aun no tiene relaciones con otras tablas esperando que se vayan creando según la necesidad del proyecto
=> Creacion de modelos, rutas y controladores  en el back de componente contactenos

client/src/app/App.jsx, client/src/pages/PetInfoCard/PetInfoCard.jsx, client/src/redux/slices/adoptionSlice.js
- 'PetsFavorites' se inicia el localStorage como un array vacio si no existe
- La pagina de detalles de mascota ahora se puede recargar sin problemas
=> fixing: favoritos y detalle mascotas

client/src/app/App.jsx, client/src/components/Footer/Footer.jsx, client/src/components/LeftSideUserCard/LeftSideUserCard.jsx, client/src/components/UserAccountMenu/UserAccountMenu.jsx, client/src/pages/UserInfoEditor/UserInfoEditor.jsx, client/src/redux/slices/petsSlice.js
- Creada la estructura basica del editor de datos de usuario
- Corregido el bug en Adoption Component que hacia peticiones infinitas al servidor
=> fixing and feature: fixing adoption bug and user info editor

client/src/pages/Contact/Contact.jsx, client/src/redux/slices/contactusSlice.js, client/src/redux/store/store.js
Funcionalidad del formulario de contactenos listo desde el front enviando datos al back y guardando en Base de datos
=> Funcionalidad del formulario de contactenos listo desde el front guar

client/src/hooks/localStorage.jsx
implemente una función para usar el local storage
=> funcion para usar el localSotage

client/src/app/App.jsx, client/src/components/Dialogs/ErrorDialog/ErrorDialog.jsx, client/src/pages/Adoptions/Adoptions.jsx, client/src/redux/slices/userSlice.js
- Se corrigio un bug en el componente ErrorDialog que rompia toda la aplicacion.
- Se corrigio un bug con el metodo de inicio de sesion de Firebase, donde no se almacenaba la sesion
=> fixing: corregidos errores en ErrorDialog y Firebase Login

api/index.js, api/src/routes/controllers/UsersControllers.js, api/src/routes/routers/routerUsuario.js
ruta resetpassword esta funcionando
=> reset password

client/src/pages/Donations/Donations.jsx
se areglo el componente stripe
=> fix stripe

client/firebase-debug.log, client/src/pages/Donations/Donations.jsx
Corregida la referencia lang faltante en la pagina donations
=> fixing: referencia lang faltante

client/src/components/CambioContraseña/CambiarContraseña.jsx
modique los cambio de contraseña
=> modicado cambio contraseña

api/src/routes/controllers/AuthControllers.js, api/src/routes/controllers/UsersControllers.js, client/src/app/App.jsx, client/src/components/CambioContraseña/CambiarContraseña.jsx, client/src/pages/SignUp/SignUp.jsx, client/src/pages/UserInfoEditor/UserInfoEditor.jsx, client/src/redux/slices/userSlice.js, client/src/resources/ErrorManager.js
Mensaje de error para los diferentes errores en login, singup y cambio de contraseña
=> feature: mensaje en los diferentes errores de login

api/src/models/Usuario.js, api/src/routes/controllers/AdoptionRequestController.js, client/src/app/App.jsx, client/src/pages/AdoptionRequestForm/AdoptionRequestForm.jsx, client/src/pages/PetInfoCard/PetInfoCard.jsx, client/src/redux/slices/petsSlice.js, client/src/services/firebaseApp.js, client/src/styles/theming.js
- Completada la conexion entre los modelos de la base de datos relacionados con AdoptionRequest
- Solo se puede solicitar una adopcion a la vez, mientras los admin. revisan la solicitud, el boton de adoptar aparece gris y sin accion.
- Cambios en tiempo real: _**esta funcion es mas util en el Deploy**_, pero si quieres verla funcionar en local, carga la pagina en dos navegadores uno al lado del otro, cuando agregas una mascota en un navegador, se actualiza la lista de mascotas en el otro de manera casi automatica.
=> feature: varias features

client/src/components/Navbar/Navbar.jsx, client/src/components/PetCard/PetCard.jsx, client/src/components/UserAccountMenu/UserAccountMenu.jsx
Ya se borran los favoritos al desloguearse, previsualiza en un Badge la cantidad de favoritos y lanza una alerta cuando se agrego o se removio de los favoritos, tambien acomode en el navbar para version mobil el link a favoritos ( antes daba a iniciar sesion)
=> feature: favorites details

client/src/components/CardViewer/CardViewer.jsx, client/src/components/PetCard/PetCard.jsx, client/src/components/TeamMemberCard/TeamMemberCard.jsx, client/src/pages/Adoptions/Adoptions.jsx
Pagina de adopciones responsiva
=> feature: pagina de adopciones responsiva

client/src/components/DataTable/DataTableUsers.jsx, client/src/pages/Adoptions/Adoptions.jsx, client/src/pages/Adoptions/Pet.Sort.js, client/src/services/api.js
PROTEGEME SEÑOOOOR CON TU ESPIRITUUUUU
=> fixing: damaged sorts

api/index.js, api/src/routes/controllers/UsersControllers.js, client/src/components/DataTable/DataTableContactUs.jsx, client/src/components/DataTable/DataTableUsers.jsx, client/src/components/DataTable/PutUser.jsx, client/src/services/api.js
añadida la propiedad role a rutas put y post de usuario y también see añadió en dashboard
=> fix dashboard

client/src/components/LeftSideUserCard/LeftSideUserCard.jsx, client/src/pages/Dashboard/Dashboard.jsx
Añadido botón para ir al dashboard en LeftSideUserCard,
Requerido volver a iniciar sesión al entrar al dashboard para comprobar si un usuario es admin o no, en esta parte no pude implementar el alert de mui, asi que metí un window.alert, si alguien lee esto y sabe como se hace puede ayudarme :c
=> fix necesarios del dashboard

client/src/components/PostAdoption/PostAdoption.jsx
corregido fallo en indicador de carga que se queda pegado cuando no se escoge una imagen, en el formularo de post adoption
=> fixing: indicador de upload infinito

client/src/components/LeftSideUserCard/LeftSideUserCard.jsx, client/src/components/Navbar/Navbar.jsx
se agrego al menu mobile el cambio de idioma, un boton para cerra, se le cambio color al nro de favoritos
=> arreglando detalles

client/src/components/Navbar/Navbar.jsx, client/src/services/api.js
cambio de posición en el logo en navbar
=> cambio de posicion del logo en el navbar

client/src/pages/Login/Login.jsx, client/src/pages/SignUp/SignUp.jsx
=> loginResponsive

client/src/pages/SignUp/SignUp.jsx, client/src/pages/SignUp/SignUp.module.css
=> responive register
